- name: Ubuntu 22.04 Playbook
  hosts: all
  become: yes

  tasks:
    - name: Install all available updates
      apt:
        upgrade: dist
        update_cache: yes
        
    - name: Install qemu-guest-agent
      apt:
        name: qemu-guest-agent
        state: present
        update_cache: true
      become: true